### ISSUE TITLE
A bug.

### ISSUE THREAD

**Issue by soyouzpanda** [AnanaGame/tictactoe#2]
In french : 
Si tu place un nombre plus grand que 8 il y a un bug, il y a trop de lignes dans le tableau. Il y a une image en dessous pour prouver. :D

In bad english :
If you put a number greater than 8, it bugs.
The table has too many lines.

![capture d ecran_2018-01-06_22-51-07](https://user-images.githubusercontent.com/23421201/34644306-4602b8fc-f334-11e7-99a7-80ec3291c656.png)

**Comment by hugolgst** [comment]
Merci beaucoup je vais régler tout ça 👍 
Thanks you very much I am going to adjust this 👍

**Comment by hugolgst** [comment]
That's good 😇

**Comment by soyouzpanda** [comment]
Nice 👍👍je vais tester ça :)
