### ISSUE TITLE
Encore un bug ...

### ISSUE THREAD

**Issue by soyouzpanda** [AnanaGame/tictactoe#3]
Bonjour !

Je voudrais prévenir d'un bug sur cette ligne (le même bug que j'avais signaler la dernière fois (https://github.com/AnanaGame/tictactoe/issues/2)) 
Le problème vient de cette ligne :
 ```      break if board.empty_place?(position) && (0..9) === position ``` (ligne 11) dans le fichier human.rb
. En effet, il faut pas mettre (0..9) mais (0..8) (je connais pas le ruby mais par déduction je pense que c'est ca) car quand on met une position de 9, ca nous indique pas d'erreur mais c'est hors des limites du "plateau de jeu"

**Comment by hugolgst** [comment]
Exact je m'en excuse j'avais fait cela rapidement je corrige ça.
